module.exports = {
    IDLE: "IDLE",
    WAITING_FOR_PLAYERS: "WAITING_FOR_PLAYERS",
    WAITING_TO_START: "WAITING_TO_START",
    ROUND_SETUP: "ROUND_SETUP",
    ROUND_START: "ROUND_START",
    ROUND_VOTE: "ROUND_VOTE",
    ROUND_VOTE_RESULT: "ROUND_VOTE_RESULT",
    ROUND_END: "ROUND_END",
    NEXT_ROUND: "NEXT_ROUND",
}