module.exports = {
    IDLE: "IDLE",
    WAITING_FOR_PLAYERS: "WAITING_FOR_PLAYERS",
    ROUND_START: "ROUND_START",
    ROUND_VOTE: "ROUND_VOTE",
    ROUND_END: "ROUND_END",
    NEXT_ROUND: "NEXT_ROUND",
}